---
abstract: 'lightweight but highly configurable logging class'
author:
  - 'Dominik Schulz <dominik.schulz@gauner.org>'
build_requires:
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Tree
requires:
  Data::Tree: 0
  English: 0
  IO::Interactive: 0
  Log::Dispatch: 0
  Log::Dispatch::Email::MailSender: 0
  Log::Dispatch::File::Locked: 0
  Log::Dispatch::Screen: 0
  Log::Dispatch::Syslog: 0
  Moose: 0
  Moose::Role: 0
  feature: 0
  mro: 0
  namespace::autoclean: 0
  perl: 5.010_000
resources:
  bugtracker: https://github.com/gittex/Log-Tree/issues
  repository: git://github.com/gittex/Log-Tree.git
version: 0.15
x_authority: cpan:TEX
